-- ====================================================================
-- Academic Management System - Sample Data
-- Sample Data Insertion Script
-- ====================================================================

-- ====================================================================
-- Insert Admin Users
-- ====================================================================

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ROLE, FIRST_NAME, LAST_NAME, EMAIL, ADMIN_ID, ACCESS_LEVEL)
VALUES (USER_SEQ.NEXTVAL, 'admin', 'admin123', 'ADMIN', 'System', 'Administrator', 'admin@university.edu', '900000001', 3);

-- ====================================================================
-- Insert Instructor Users
-- ====================================================================

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ROLE, FIRST_NAME, LAST_NAME, EMAIL, INSTRUCTOR_ID, DEPARTMENT, OFFICE_LOCATION, PHONE_EXTENSION, SPECIALIZATION)
VALUES (USER_SEQ.NEXTVAL, 'dr.ahmad', 'pass123', 'INSTRUCTOR', 'Ahmad', 'Al-Salem', 'ahmad.salem@university.edu', '100000001', 'Computer Science', 'CS-301', '1234', 'Software Engineering');

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ROLE, FIRST_NAME, LAST_NAME, EMAIL, INSTRUCTOR_ID, DEPARTMENT, OFFICE_LOCATION, PHONE_EXTENSION, SPECIALIZATION)
VALUES (USER_SEQ.NEXTVAL, 'dr.fatima', 'pass123', 'INSTRUCTOR', 'Fatima', 'Al-Rashid', 'fatima.rashid@university.edu', '100000002', 'Computer Science', 'CS-302', '1235', 'Database Systems');

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ROLE, FIRST_NAME, LAST_NAME, EMAIL, INSTRUCTOR_ID, DEPARTMENT, OFFICE_LOCATION, PHONE_EXTENSION, SPECIALIZATION)
VALUES (USER_SEQ.NEXTVAL, 'dr.omar', 'pass123', 'INSTRUCTOR', 'Omar', 'Al-Mansour', 'omar.mansour@university.edu', '100000003', 'Mathematics', 'MATH-201', '1236', 'Calculus');

-- ====================================================================
-- Insert Student Users
-- ====================================================================

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ROLE, FIRST_NAME, LAST_NAME, EMAIL, STUDENT_ID, MAJOR, GPA, ENROLLMENT_YEAR, TOTAL_CREDITS)
VALUES (USER_SEQ.NEXTVAL, 'lujain', 'pass123', 'STUDENT', 'Lujain', 'Al-Harbi', 'lujain@student.edu', '202400001', 'Computer Science', 3.75, 2024, 15);

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ROLE, FIRST_NAME, LAST_NAME, EMAIL, STUDENT_ID, MAJOR, GPA, ENROLLMENT_YEAR, TOTAL_CREDITS)
VALUES (USER_SEQ.NEXTVAL, 'sara', 'pass123', 'STUDENT', 'Sara', 'Al-Qahtani', 'sara@student.edu', '202400002', 'Computer Science', 3.90, 2024, 18);

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ROLE, FIRST_NAME, LAST_NAME, EMAIL, STUDENT_ID, MAJOR, GPA, ENROLLMENT_YEAR, TOTAL_CREDITS)
VALUES (USER_SEQ.NEXTVAL, 'khalid', 'pass123', 'STUDENT', 'Khalid', 'Al-Otaibi', 'khalid@student.edu', '202300001', 'Engineering', 3.50, 2023, 30);

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ROLE, FIRST_NAME, LAST_NAME, EMAIL, STUDENT_ID, MAJOR, GPA, ENROLLMENT_YEAR, TOTAL_CREDITS)
VALUES (USER_SEQ.NEXTVAL, 'rand', 'pass123', 'STUDENT', 'Rand', 'Al-Zahrani', 'rand@student.edu', '202400003', 'Mathematics', 3.85, 2024, 12);

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ROLE, FIRST_NAME, LAST_NAME, EMAIL, STUDENT_ID, MAJOR, GPA, ENROLLMENT_YEAR, TOTAL_CREDITS)
VALUES (USER_SEQ.NEXTVAL, 'mohammed', 'pass123', 'STUDENT', 'Mohammed', 'Al-Shehri', 'mohammed@student.edu', '202400004', 'Computer Science', 3.60, 2024, 15);

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ROLE, FIRST_NAME, LAST_NAME, EMAIL, STUDENT_ID, MAJOR, GPA, ENROLLMENT_YEAR, TOTAL_CREDITS)
VALUES (USER_SEQ.NEXTVAL, 'noura', 'pass123', 'STUDENT', 'Noura', 'Al-Malki', 'noura@student.edu', '202300002', 'Computer Science', 3.95, 2023, 36);

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ROLE, FIRST_NAME, LAST_NAME, EMAIL, STUDENT_ID, MAJOR, GPA, ENROLLMENT_YEAR, TOTAL_CREDITS)
VALUES (USER_SEQ.NEXTVAL, 'abdulaziz', 'pass123', 'STUDENT', 'Abdulaziz', 'Al-Ghamdi', 'abdulaziz@student.edu', '202400005', 'Engineering', 3.40, 2024, 18);

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ROLE, FIRST_NAME, LAST_NAME, EMAIL, STUDENT_ID, MAJOR, GPA, ENROLLMENT_YEAR, TOTAL_CREDITS)
VALUES (USER_SEQ.NEXTVAL, 'maha', 'pass123', 'STUDENT', 'Maha', 'Al-Dawsari', 'maha@student.edu', '202400006', 'Mathematics', 3.70, 2024, 15);

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ROLE, FIRST_NAME, LAST_NAME, EMAIL, STUDENT_ID, MAJOR, GPA, ENROLLMENT_YEAR, TOTAL_CREDITS)
VALUES (USER_SEQ.NEXTVAL, 'fahad', 'pass123', 'STUDENT', 'Fahad', 'Al-Mutairi', 'fahad@student.edu', '202300003', 'Computer Science', 3.55, 2023, 33);

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ROLE, FIRST_NAME, LAST_NAME, EMAIL, STUDENT_ID, MAJOR, GPA, ENROLLMENT_YEAR, TOTAL_CREDITS)
VALUES (USER_SEQ.NEXTVAL, 'reem', 'pass123', 'STUDENT', 'Reem', 'Al-Amri', 'reem@student.edu', '202400007', 'Computer Science', 3.80, 2024, 12);

-- ====================================================================
-- Insert Courses
-- ====================================================================

-- Get instructor IDs for foreign key references
INSERT INTO COURSES (COURSE_ID, COURSE_CODE, COURSE_NAME, CREDIT_HOURS, INSTRUCTOR_ID, SEMESTER, YEAR, MAX_CAPACITY)
VALUES (COURSE_SEQ.NEXTVAL, 'CS101', 'Introduction to Computer Science', 3,
    (SELECT USER_ID FROM USERS WHERE USERNAME = 'dr.ahmad'), 'Fall', 2024, 30);

INSERT INTO COURSES (COURSE_ID, COURSE_CODE, COURSE_NAME, CREDIT_HOURS, INSTRUCTOR_ID, SEMESTER, YEAR, MAX_CAPACITY)
VALUES (COURSE_SEQ.NEXTVAL, 'CS102', 'Data Structures', 4,
    (SELECT USER_ID FROM USERS WHERE USERNAME = 'dr.ahmad'), 'Fall', 2024, 25);

INSERT INTO COURSES (COURSE_ID, COURSE_CODE, COURSE_NAME, CREDIT_HOURS, INSTRUCTOR_ID, SEMESTER, YEAR, MAX_CAPACITY)
VALUES (COURSE_SEQ.NEXTVAL, 'CS201', 'Database Systems', 3,
    (SELECT USER_ID FROM USERS WHERE USERNAME = 'dr.fatima'), 'Fall', 2024, 28);

INSERT INTO COURSES (COURSE_ID, COURSE_CODE, COURSE_NAME, CREDIT_HOURS, INSTRUCTOR_ID, SEMESTER, YEAR, MAX_CAPACITY)
VALUES (COURSE_SEQ.NEXTVAL, 'CS301', 'Advanced Programming', 4,
    (SELECT USER_ID FROM USERS WHERE USERNAME = 'dr.ahmad'), 'Fall', 2024, 20);

INSERT INTO COURSES (COURSE_ID, COURSE_CODE, COURSE_NAME, CREDIT_HOURS, INSTRUCTOR_ID, SEMESTER, YEAR, MAX_CAPACITY)
VALUES (COURSE_SEQ.NEXTVAL, 'MATH201', 'Calculus I', 4,
    (SELECT USER_ID FROM USERS WHERE USERNAME = 'dr.omar'), 'Fall', 2024, 35);

INSERT INTO COURSES (COURSE_ID, COURSE_CODE, COURSE_NAME, CREDIT_HOURS, INSTRUCTOR_ID, SEMESTER, YEAR, MAX_CAPACITY)
VALUES (COURSE_SEQ.NEXTVAL, 'MATH202', 'Calculus II', 4,
    (SELECT USER_ID FROM USERS WHERE USERNAME = 'dr.omar'), 'Fall', 2024, 30);

INSERT INTO COURSES (COURSE_ID, COURSE_CODE, COURSE_NAME, CREDIT_HOURS, INSTRUCTOR_ID, SEMESTER, YEAR, MAX_CAPACITY)
VALUES (COURSE_SEQ.NEXTVAL, 'CS202', 'Algorithms', 3,
    (SELECT USER_ID FROM USERS WHERE USERNAME = 'dr.fatima'), 'Fall', 2024, 25);

INSERT INTO COURSES (COURSE_ID, COURSE_CODE, COURSE_NAME, CREDIT_HOURS, INSTRUCTOR_ID, SEMESTER, YEAR, MAX_CAPACITY)
VALUES (COURSE_SEQ.NEXTVAL, 'CS150', 'Web Development', 3,
    (SELECT USER_ID FROM USERS WHERE USERNAME = 'dr.ahmad'), 'Fall', 2024, 30);

-- ====================================================================
-- Insert Enrollments
-- ====================================================================

-- Student: Lujain (202400001)
INSERT INTO ENROLLMENTS (ENROLLMENT_ID, STUDENT_ID, COURSE_ID, ENROLLMENT_DATE, STATUS)
VALUES (ENROLLMENT_SEQ.NEXTVAL,
    (SELECT USER_ID FROM USERS WHERE STUDENT_ID = '202400001'),
    (SELECT COURSE_ID FROM COURSES WHERE COURSE_CODE = 'CS101'),
    SYSDATE, 'COMPLETED');

INSERT INTO ENROLLMENTS (ENROLLMENT_ID, STUDENT_ID, COURSE_ID, ENROLLMENT_DATE, STATUS)
VALUES (ENROLLMENT_SEQ.NEXTVAL,
    (SELECT USER_ID FROM USERS WHERE STUDENT_ID = '202400001'),
    (SELECT COURSE_ID FROM COURSES WHERE COURSE_CODE = 'CS102'),
    SYSDATE, 'ENROLLED');

INSERT INTO ENROLLMENTS (ENROLLMENT_ID, STUDENT_ID, COURSE_ID, ENROLLMENT_DATE, STATUS)
VALUES (ENROLLMENT_SEQ.NEXTVAL,
    (SELECT USER_ID FROM USERS WHERE STUDENT_ID = '202400001'),
    (SELECT COURSE_ID FROM COURSES WHERE COURSE_CODE = 'MATH201'),
    SYSDATE, 'COMPLETED');

-- Student: Sara (202400002)
INSERT INTO ENROLLMENTS (ENROLLMENT_ID, STUDENT_ID, COURSE_ID, ENROLLMENT_DATE, STATUS)
VALUES (ENROLLMENT_SEQ.NEXTVAL,
    (SELECT USER_ID FROM USERS WHERE STUDENT_ID = '202400002'),
    (SELECT COURSE_ID FROM COURSES WHERE COURSE_CODE = 'CS101'),
    SYSDATE, 'COMPLETED');

INSERT INTO ENROLLMENTS (ENROLLMENT_ID, STUDENT_ID, COURSE_ID, ENROLLMENT_DATE, STATUS)
VALUES (ENROLLMENT_SEQ.NEXTVAL,
    (SELECT USER_ID FROM USERS WHERE STUDENT_ID = '202400002'),
    (SELECT COURSE_ID FROM COURSES WHERE COURSE_CODE = 'CS201'),
    SYSDATE, 'ENROLLED');

INSERT INTO ENROLLMENTS (ENROLLMENT_ID, STUDENT_ID, COURSE_ID, ENROLLMENT_DATE, STATUS)
VALUES (ENROLLMENT_SEQ.NEXTVAL,
    (SELECT USER_ID FROM USERS WHERE STUDENT_ID = '202400002'),
    (SELECT COURSE_ID FROM COURSES WHERE COURSE_CODE = 'MATH201'),
    SYSDATE, 'COMPLETED');

-- Student: Khalid (202300001)
INSERT INTO ENROLLMENTS (ENROLLMENT_ID, STUDENT_ID, COURSE_ID, ENROLLMENT_DATE, STATUS)
VALUES (ENROLLMENT_SEQ.NEXTVAL,
    (SELECT USER_ID FROM USERS WHERE STUDENT_ID = '202300001'),
    (SELECT COURSE_ID FROM COURSES WHERE COURSE_CODE = 'CS301'),
    SYSDATE, 'ENROLLED');

INSERT INTO ENROLLMENTS (ENROLLMENT_ID, STUDENT_ID, COURSE_ID, ENROLLMENT_DATE, STATUS)
VALUES (ENROLLMENT_SEQ.NEXTVAL,
    (SELECT USER_ID FROM USERS WHERE STUDENT_ID = '202300001'),
    (SELECT COURSE_ID FROM COURSES WHERE COURSE_CODE = 'CS202'),
    SYSDATE, 'ENROLLED');

-- Student: Mohammed (202400004)
INSERT INTO ENROLLMENTS (ENROLLMENT_ID, STUDENT_ID, COURSE_ID, ENROLLMENT_DATE, STATUS)
VALUES (ENROLLMENT_SEQ.NEXTVAL,
    (SELECT USER_ID FROM USERS WHERE STUDENT_ID = '202400004'),
    (SELECT COURSE_ID FROM COURSES WHERE COURSE_CODE = 'CS101'),
    SYSDATE, 'COMPLETED');

INSERT INTO ENROLLMENTS (ENROLLMENT_ID, STUDENT_ID, COURSE_ID, ENROLLMENT_DATE, STATUS)
VALUES (ENROLLMENT_SEQ.NEXTVAL,
    (SELECT USER_ID FROM USERS WHERE STUDENT_ID = '202400004'),
    (SELECT COURSE_ID FROM COURSES WHERE COURSE_CODE = 'CS150'),
    SYSDATE, 'ENROLLED');

-- Student: Noura (202300002)
INSERT INTO ENROLLMENTS (ENROLLMENT_ID, STUDENT_ID, COURSE_ID, ENROLLMENT_DATE, STATUS)
VALUES (ENROLLMENT_SEQ.NEXTVAL,
    (SELECT USER_ID FROM USERS WHERE STUDENT_ID = '202300002'),
    (SELECT COURSE_ID FROM COURSES WHERE COURSE_CODE = 'CS301'),
    SYSDATE, 'ENROLLED');

-- ====================================================================
-- Insert Grades (for completed enrollments)
-- ====================================================================

-- Grades for Lujain
INSERT INTO GRADES (GRADE_ID, ENROLLMENT_ID, GRADE, NUMERIC_GRADE, GRADE_DATE)
VALUES (GRADE_SEQ.NEXTVAL,
    (SELECT ENROLLMENT_ID FROM ENROLLMENTS WHERE STUDENT_ID = (SELECT USER_ID FROM USERS WHERE STUDENT_ID = '202400001')
     AND COURSE_ID = (SELECT COURSE_ID FROM COURSES WHERE COURSE_CODE = 'CS101')),
    'A', 4.00, SYSDATE);

INSERT INTO GRADES (GRADE_ID, ENROLLMENT_ID, GRADE, NUMERIC_GRADE, GRADE_DATE)
VALUES (GRADE_SEQ.NEXTVAL,
    (SELECT ENROLLMENT_ID FROM ENROLLMENTS WHERE STUDENT_ID = (SELECT USER_ID FROM USERS WHERE STUDENT_ID = '202400001')
     AND COURSE_ID = (SELECT COURSE_ID FROM COURSES WHERE COURSE_CODE = 'MATH201')),
    'B+', 3.33, SYSDATE);

-- Grades for Sara
INSERT INTO GRADES (GRADE_ID, ENROLLMENT_ID, GRADE, NUMERIC_GRADE, GRADE_DATE)
VALUES (GRADE_SEQ.NEXTVAL,
    (SELECT ENROLLMENT_ID FROM ENROLLMENTS WHERE STUDENT_ID = (SELECT USER_ID FROM USERS WHERE STUDENT_ID = '202400002')
     AND COURSE_ID = (SELECT COURSE_ID FROM COURSES WHERE COURSE_CODE = 'CS101')),
    'A', 4.00, SYSDATE);

INSERT INTO GRADES (GRADE_ID, ENROLLMENT_ID, GRADE, NUMERIC_GRADE, GRADE_DATE)
VALUES (GRADE_SEQ.NEXTVAL,
    (SELECT ENROLLMENT_ID FROM ENROLLMENTS WHERE STUDENT_ID = (SELECT USER_ID FROM USERS WHERE STUDENT_ID = '202400002')
     AND COURSE_ID = (SELECT COURSE_ID FROM COURSES WHERE COURSE_CODE = 'MATH201')),
    'A', 4.00, SYSDATE);

-- Grades for Mohammed
INSERT INTO GRADES (GRADE_ID, ENROLLMENT_ID, GRADE, NUMERIC_GRADE, GRADE_DATE)
VALUES (GRADE_SEQ.NEXTVAL,
    (SELECT ENROLLMENT_ID FROM ENROLLMENTS WHERE STUDENT_ID = (SELECT USER_ID FROM USERS WHERE STUDENT_ID = '202400004')
     AND COURSE_ID = (SELECT COURSE_ID FROM COURSES WHERE COURSE_CODE = 'CS101')),
    'B+', 3.33, SYSDATE);

-- ====================================================================
-- Data Insertion Complete
-- ====================================================================

COMMIT;
